Repository pq-code-package/mldsa-native, pull requests merged in 2025-04, with the labels that each got.

#88 Add InsertBraces option for clang-format
  .clang-format
  mldsa/fips202/fips202.c
  mldsa/packing.c
  mldsa/poly.c
  mldsa/polyvec.c
  mldsa/rounding.c
  mldsa/sign.c
  test/acvp_mldsa.c
  test/bench_mldsa.c
Labels: enhancement

#97 Move and clarify comments in rounding.c to rounding.h
  mldsa/rounding.c
  mldsa/rounding.h
Labels: documentation

#50 Adds benchmarking on Raspberry Pi 4 (Cortex-A72)
  .github/actions/bench/action.yml
  .github/workflows/bench.yml
Labels: benchmark

#151 CBMC: Add contracts and proofs for various polyvec functions
  mldsa/poly.c
  mldsa/poly.h
  mldsa/polyvec.c
  mldsa/polyvec.h
  proofs/cbmc/polyveck_add/Makefile
  proofs/cbmc/polyveck_add/polyveck_add_harness.c
  proofs/cbmc/polyveck_pack_w1/Makefile
  proofs/cbmc/polyveck_pack_w1/polyveck_pack_w1_harness.c
  proofs/cbmc/polyveck_reduce/Makefile
  proofs/cbmc/polyveck_reduce/polyveck_reduce_harness.c
  proofs/cbmc/polyveck_sub/Makefile
  proofs/cbmc/polyveck_sub/polyveck_sub_harness.c
  proofs/cbmc/polyveck_use_hint/Makefile
  proofs/cbmc/polyveck_use_hint/polyveck_use_hint_harness.c
  proofs/cbmc/polyvecl_add/Makefile
  proofs/cbmc/polyvecl_add/polyvecl_add_harness.c
  proofs/cbmc/polyvecl_reduce/Makefile
  proofs/cbmc/polyvecl_reduce/polyvecl_reduce_harness.c
Labels: benchmark

#177 Benchmarking CI: Add Mac Mini M1
  .github/workflows/bench.yml
Labels: benchmark

#52 Add benchmarking (Raspberry Pi 5, Cortex-A55, Banana PI F3)
  .github/workflows/bench.yml
Labels: benchmark

#186 CBMC: Add contract and proof for polyvecl_invntt_tomont
  mldsa/polyvec.c
  mldsa/polyvec.h
  proofs/cbmc/polyvecl_invntt_tomont/Makefile
  proofs/cbmc/polyvecl_invntt_tomont/polyvecl_invntt_tomont_harness.c
Labels: cbmc
